In [14]:
import os
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as ans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report
print("all file imported")

all file imported

In [15]:
df=pd.read_csv('test_healthcare_data.csv')

In [16]:
df.head()

,age,bmi,glucose,blood_pressure,skin_thickness,insulin,pregnancies,diabetes_pedigree,cholesterol,heart_rate
0,28,18.529573,139.261641,135.076330,36.033101,300.000000,2,2.337479,214.153905,71.377501
1,59,19.806059,70.000000,135.674507,23.018947,225.979993,2,1.042105,182.935183,79.274539
2,49,33.718561,141.367939,101.762222,51.007021,96.991671,2,1.236223,100.000000,58.636124
3,22,21.009686,197.949118,92.462627,35.882969,14.000000,4,1.573590,183.985161,87.087409
4,36,25.148416,119.261221,109.606899,28.936927,218.128329,3,1.059470,153.669778,70.531484

In [17]:
# glucose_risk=(df['glucose']>130).astype(int)
# bp_risk =(df['blood_pressure']>135).astype(int)
# cholestrol_risk =(df['cholesterol']>200).astype(int)
# bmi_risk =(df['bmi']>28).astype(int)
# age_risk =(df['age']>60).astype(int)
# total_risl_score=glucose_risk+bp_risk+cholestrol_risk+bmi_risk+age_risk+age_risk
# df['risk_level']=(total_risl_score>=2).astype(int)
# # print(total_risl_score).
# print("orignal ")
# print(df['risk_level'].value_count())

glucose_risk=(df['glucose']>130).astype(int)
bp_risk=(df['blood_pressure']>135).astype(int)
cholesterol_risk=(df['cholesterol']>200).astype(int)
bmi_risk=(df['bmi']>28).astype(int)
age_risk=(df['age']>60).astype(int)
total_risk_score=glucose_risk+bp_risk+cholesterol_risk+bmi_risk+age_risk
df['risk_level']=(total_risk_score>=2).astype(int)
print(df.risk_level)
print(df['risk_level'].value_counts())
print(1,0)

0      1
1      0
2      1
3      0
4      0
      ..
995    0
996    0
997    1
998    0
999    0
Name: risk_level, Length: 1000, dtype: int64
risk_level
1    561
0    439
Name: count, dtype: int64
1 0

In [18]:
df

,age,bmi,glucose,blood_pressure,skin_thickness,insulin,pregnancies,diabetes_pedigree,cholesterol,heart_rate,risk_level
0,28,18.529573,139.261641,135.076330,36.033101,300.000000,2,2.337479,214.153905,71.377501,1
1,59,19.806059,70.000000,135.674507,23.018947,225.979993,2,1.042105,182.935183,79.274539,0
2,49,33.718561,141.367939,101.762222,51.007021,96.991671,2,1.236223,100.000000,58.636124,1
3,22,21.009686,197.949118,92.462627,35.882969,14.000000,4,1.573590,183.985161,87.087409,0
4,36,25.148416,119.261221,109.606899,28.936927,218.128329,3,1.059470,153.669778,70.531484,0
...,...,...,...,...,...,...,...,...,...,...,...
995,27,23.412734,91.722025,122.210462,25.350112,191.203926,4,0.798004,275.541666,57.523865,0
996,19,23.987993,106.721532,124.855416,29.017761,112.730481,2,0.188133,197.539646,87.017773,0
997,33,33.595603,99.393543,131.028916,18.416833,83.403162,0,0.536103,243.941805,80.815828,1
998,44,28.227965,106.160759,111.259273,20.302552,137.782263,3,1.904634,175.709567,72.862508,0
999,49,23.798244,108.189048,110.889939,28.664343,198.749236,2,1.410156,180.926645,92.097056,0

In [19]:
df.columns

Index(['age', 'bmi', 'glucose', 'blood_pressure', 'skin_thickness', 'insulin',
       'pregnancies', 'diabetes_pedigree', 'cholesterol', 'heart_rate',
       'risk_level'],
      dtype='str')

In [20]:
print(df['risk_level'].value_counts())

risk_level
1    561
0    439
Name: count, dtype: int64

In [21]:
x=df.drop('risk_level',axis=1)
y=df['risk_level']
print("Feature (X) columns: ",list(x.columns))

Feature (X) columns:  ['age', 'bmi', 'glucose', 'blood_pressure', 'skin_thickness', 'insulin', 'pregnancies', 'diabetes_pedigree', 'cholesterol', 'heart_rate']

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(f"training set size : {x_train.shape[0]} patients")
print(f"testing set size :{x_test.shape[0]} patients ")

training set size : 800 patients
testing set size :200 patients

In [23]:
model=RandomForestClassifier(n_estimators=100,random_state=42,max_depth=6,n_jobs=-1)
model.fit(x_train,y_train)
print("random frorest clasier trained ")

random frorest clasier trained

In [24]:
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"model pe=redict accuracy with noise :{accuracy*100:.2f}%")
print("\n classification repot")
print(classification_report(y_test,y_pred))

model pe=redict accuracy with noise :98.50%

 classification repot
              precision    recall  f1-score   support

           0       0.99      0.98      0.98        93
           1       0.98      0.99      0.99       107

    accuracy                           0.98       200
   macro avg       0.99      0.98      0.98       200
weighted avg       0.99      0.98      0.98       200

In [25]:
os.makedirs("model",exist_ok=True)
model_data={'model':model ,'features':list(x.columns)}
model_filepath ="model/healthcare_model.pkl"
with open(model_filepath,'wb') as file:
    pickle.dump(model_data,file)